Led (working code)
Prosper-FRC/template-talon_standard pull request #9
Opened 2024-12-06 00:18 UTC by JamesMcNulty7

2024-12-09 23:32 UTC, JamesMcNulty7 commented on build.gradle
> +    id "edu.wpi.first.GradleRIO" version "2024.1.1"
Not entirely sure but I changed it back to 3.2

2024-12-13 00:07 UTC, mduffor commented on src/main/java/frc/robot/LED.java
> +        if(intakeSensor.getValue()){
So the sensor should be separate from the LED class.  Sensors sense things, LEDs light things The hookup should be at a higher level  We may need the logic of our auto commands or teleop helper commands to pull in sensor values (is note loaded), so we need the sensor to be more stand-alone/modular.

2024-12-13 01:18 UTC, mduffor requested changes

2024-12-13 01:18 UTC, mduffor commented on src/main/java/frc/robot/ILED.java
> +    public void setSingleRGB(int index, int r, int g, int b);
Add comments giving the acceptable range of values.  i.e. 0 to 255

2025-01-03 16:45 UTC, mduffor approved these changes

2025-01-03 17:35 UTC, closed without merging